- name: demo on data types
  hosts: local
  connection: local
  vars:
    PROGRAM: "DevSecOps with AWS" #string
    DURATION: 140 #int/number
    IS_LIVE: true #bool
    DETAILS: #map/directory
      MONTHS: 4
      TRAINER: "sivakumar Reddy"
    TOPICS: #list -/[]
      - Ansible
      - Docker
      - Kubernetes
      - AWS
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: 
         program: {{ PROGRAM }}
         duration: {{ DURATION }}
          is_live: {{ IS_LIVE }}
          details: {{ DETAILS }}
          topics: {{ TOPICS }}